/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/hoodie4.glb -o temp_hoodie_nodes.tsx 
Author: Danielsuta37 (https://sketchfab.com/Danielsuta37)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hoodie-7a5a103f192f406db0739edb771ffce9
Title: Hoodie
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
  }
  materials: {
    ['Material238904.005']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/hoodie4.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material238904.005']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material238904.005']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material238904.005']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material238904.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/hoodie4.glb')
